# Generated by Django 3.0 on 2020-12-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new1',
            name='conte',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='new1',
            name='head',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='new1',
            name='image',
            field=models.ImageField(default=None, upload_to='static/img'),
        ),
    ]
